### ISSUE TITLE
posthtml plugin

### ISSUE THREAD

**Issue by stevenvachon** [code-and-send/email-remove-unused-css#1]
Why didn't you just make it a plugin?

**Comment by revelt** [comment]
I aim to separate the library from shells, Grunt, Gulp, PostHTML/CSS or others, because one universal library can empower many plugins. For example, Gulp plugin is only a shell, a wrapper now.

By the way, Gulp plugin is ready, it's here: https://github.com/code-and-send/gulp-email-remove-unused-css

PostHTML plugin is next on my to-do list, unless somebody contributes it first 😀

**Comment by stevenvachon** [comment]
You could build this library like [htmlnano](https://npmjs.com/htmlnano), where it can be used both independently and as a posthtml plugin.

**Comment by revelt** [comment]
I didn't know it's possible. I'll investigate. Thanks for the idea!

**Comment by revelt** [comment]
An update. PostCSS plugin release is very close. I've got the core, but testing setup is new takes time to code up. Also, since it's new boilerplate I can't reuse anything, so more work in Readme/package.json.

**Comment by revelt** [comment]
Done, plugin is online:
https://github.com/code-and-send/posthtml-email-remove-unused-css
